### ISSUE TITLE
InvalidArgumentError: No OpKernel was registered to support Op 'FlowWarp' with these attrs.  

### ISSUE THREAD

**Issue by alasin** [sampepose/flownet2-tf#17]
While running the given test command, I'm getting this error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/anuj/motion/flownet2-tf/src/flownet2/test.py", line 51, in <module>
    main()
  File "/data/anuj/motion/flownet2-tf/src/flownet2/test.py", line 18, in main
    out_path=FLAGS.out,
  File "src/net.py", line 68, in test
    saver.restore(sess, checkpoint)
  File "/home/anuj/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/anuj/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/anuj/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/anuj/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/anuj/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FlowWarp' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'**
**[[Node: FlowNet2/FlowWarp = FlowWarp[](ExpandDims_1, FlowNet2/FlowNetSD/ResizeBilinear)]]**

If I use the network flownet2-s or flownet2-sd, it works fine.

I'm using TF 1.2.0, CUDA 8.0, CuDNN 7 on Ubuntu 16.04.

**Comment by laim9006** [comment]
Same problem.

**Comment by soomanco** [comment]
Same problem.

**Comment by laim9006** [comment]
I have been tried again in Nvidia-Docker environment.
Using Image: Ubuntu16.04 + CUDA8.0 +CuDNN 5.1
And tensorflow-gpu 1.2.1 + Python2.7

First time I use tensorflow(not gpu version) , it would succeed in make but has this problem.
When I use tensorflow-gpu==1.2.1 and the same environment above, it works fine.

**Comment by soomanco** [comment]
Okay. I finally found the issue and resolved the problem. I originally had tensorflow ver 1.4.0 on my linux and I downgraded it to 1.2.0 in order to run this flownet2. My issue was that I still had tensorflow-gpu ver 1.4.0 and after downgrading it to 1.2.0 it worked like nothing happened before. 

So you need tensorflow==1.2.0, tensorflow-gpu==1.2.0 and these can be done by

pip install tensorflow==1.2.0
pip install tensorflow-gpu==1.2.0

Hope this resolves your problems as well

**Comment by ceciliavision** [comment]
@ssm9462 works for me. Thanks!
