### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'reader_kwargs'

### ISSUE THREAD

**Issue by xiongdemao** [sampepose/flownet2-tf#23]
/home/ne5/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/colors.py:680: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  not cbook.is_string_like(colors[0]):
Traceback (most recent call last):
  File "/home/ne5/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ne5/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ne5/test/flownet2-tf-master/src/flownet_css/train.py", line 10, in <module>
    input_a, input_b, flow = load_batch(FLYING_CHAIRS_DATASET_CONFIG, 'sample', net.global_step)
  File "src/dataloader.py", line 235, in load_batch
    reader_kwargs=reader_kwargs)
TypeError: __init__() got an unexpected keyword argument 'reader_kwargs'

**Comment by xiongdemao** [comment]
when run
```
  python -m src.flownet_css.train
```
