### ISSUE TITLE
nvcc fatal   : Unknown option 'std'

### ISSUE THREAD

**Issue by Benzzzxxx** [sampepose/flownet2-tf#42]
in test.py file has code line 11
tf.resource_loader.get_path_to_datafile("./src/ops/build/preprocessing.so"))
but in the ./src/ops/build/ directory has no this file"preprocessing.so"

$ python test.py
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    tf.resource_loader.get_path_to_datafile("./src/ops/build/preprocessing.so"))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./src/ops/build/preprocessing.so: cannot open shared object file: No such file or directory

because i don't use "make" to compile the project.But after I enter "make"
$ make
nvcc -g -std=c++11 -I`python -c "import tensorflow; print(tensorflow.sysconfig.get_include())"` -I"/usr/local/cuda/include" -DGOOGLE_CUDA=1 -D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__ -D_GLIBCXX_USE_CXX11_ABI=0 -c src/ops/preprocessing/kernels/data_augmentation.cu.cc -x cu -Xcompiler -fPIC  -o src/ops/build/data_augmentation.o
nvcc fatal   : Unknown option 'std'
make: *** [preprocessing] 错误 255

How to solve this question? Thank you very much.

**Comment by Iamanorange** [comment]
Try to install a newer CUDA toolkit.
CUDA 9.0 works on my system.
