### ISSUE TITLE
convert image data to tfrecord file

### ISSUE THREAD

**Issue by xiaojifeng** [sampepose/flownet2-tf#47]
I'm preparing the training data by converting images to tfrecord file. Then i replaced the oringinal tfrecord file "fc_sampe.tfrecord" with it. After that i run the command line 'python -m src.flownet2.train' to train the model, but i got the error messages:
 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jixi/test/flownet2-tf/src/flownet2/train.py", line 24, in <module>
    './checkpoints/FlowNetSD/flownet-SD.ckpt-0': ('FlowNet2/FlowNetSD', 'FlowNet2')
  File "/home/jixi/test/flownet2-tf/src/net.py", line 154, in train
    number_of_steps=training_schedule['max_iter']
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 784, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: inflate() failed with error -3: incorrect header check
         [[Node: load_batch/parallel_read/ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](load_batch/parallel_read/TFRecordReaderV2_2, load_batch/parallel_read/filenames)]]

and here is my code to generate the tfrecord data:

def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

tfrecords_filename = 'FlyingChairs_test.tfrecords'
tfrecords_path = 'tfrecords/'
writer = tf.python_io.TFRecordWriter(tfrecords_path+tfrecords_filename)
original_images = []

for img_path_1, img_path_2, flow_path in filename_pairs:
    
    img_1 = io.imread(img_path_1).astype('float64')
    img_2 = io.imread(img_path_2).astype('float64')
    flow = fe.readFlo(flow_path)
    
    original_images.append((img_1, img_2, flow))
    
    img_1_raw = img_1.tostring()
    img_2_raw = img_2.tostring()
    flow_raw = flow.tostring()
    
    example = tf.train.Example(features=tf.train.Features(feature={
        'image_a': _bytes_feature(img_1_raw),
        'image_b': _bytes_feature(img_2_raw),
        'flow': _bytes_feature(flow_raw)}))
    
    writer.write(example.SerializeToString())
    
writer.close()

can anyone help me how to generate the training data correctly?

**Comment by xiaojifeng** [comment]
found result: use scripts/convert_fc_to_tfrecords.py to generate the tfrecord file.
