### ISSUE TITLE
Getting png error

### ISSUE THREAD

**Issue by ADHARACSM** [sampepose/flownet2-tf#63]
Platform : Windows 10
I tried running 
python -m src.flownet2.test --input_a data/samples/0img0.ppm --input_b data/samples/0img1.ppm --out ./

I get the error 
ModuleNotFoundError: No module named 'png'

Although I have installed pypng
Is this code compatible with python3.6.6?

Output
(tensorflow) D:\CSM\Spring2019\tensorflow\flownet2-tf>python -m src.flownet2.test --input_a data/samples/0img0.ppm --input_b data/samples/0img1.ppm --out ./
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\CSM\Spring2019\tensorflow\flownet2-tf\src\flownet2\test.py", line 3, in <module>
    from ..net import Mode
  File "D:\CSM\Spring2019\tensorflow\flownet2-tf\src\net.py", line 5, in <module>
    from .flowlib import flow_to_image, write_flow
  File "D:\CSM\Spring2019\tensorflow\flownet2-tf\src\flowlib.py", line 10, in <module>
    import png
ModuleNotFoundError: No module named 'png'

**Comment by Iamanorange** [comment]
```shell
pip install pypng
```

**Comment by ADHARACSM** [comment]
Could install.
