### ISSUE TITLE
No OpKernel was registered to support Op 'FlowWarp' with these attrs. 

### ISSUE THREAD

**Issue by chuchienshu** [sampepose/flownet2-tf#7]
```
python -m src.flownet2.test --input_a data/samples/0img0.ppm --input_b data/samples/0img1.ppm --out ./
2017-09-13 13:48:11.827500: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 13:48:11.827522: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 13:48:11.827526: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 13:48:11.827529: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 13:48:11.827533: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet2/test.py", line 51, in <module>
    main()
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet2/test.py", line 18, in main
    out_path=FLAGS.out,
  File "src/net.py", line 68, in test
    saver.restore(sess, checkpoint)
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FlowWarp' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: FlowNet2/FlowWarp = FlowWarp[](ExpandDims_1, FlowNet2/FlowNetSD/ResizeBilinear)]]

Caused by op u'FlowNet2/FlowWarp', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet2/test.py", line 51, in <module>
    main()
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet2/test.py", line 18, in main
    out_path=FLAGS.out,
  File "src/net.py", line 62, in test
    predictions = self.model(inputs, training_schedule)
  File "src/flownet2/flownet2.py", line 33, in model
    flow_warp_sd = flow_warp(inputs['input_b'], net_sd_predictions['flow'])
  File "src/flow_warp.py", line 8, in flow_warp
    return _flow_warp_ops.flow_warp(image, flow)
  File "<string>", line 30, in flow_warp
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/chuchienshu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FlowWarp' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: FlowNet2/FlowWarp = FlowWarp[](ExpandDims_1, FlowNet2/FlowNetSD/ResizeBilinear)]]

```
The version of tensorflow is 1.2.0.thanks a lot！

**Comment by chuchienshu** [comment]
Actually, I have changed the code at line 4 of correlation.py from `tf.resource_loader.get_path_to_datafile("./ops/build/correlation.so"))`to `tf.resource_loader.get_path_to_datafile("ops/build/correlation.so"))`.
cause the former has the same issue too.

**Comment by chuchienshu** [comment]
I forget this step `make all.`
sorry.

**Comment by sampepose** [comment]
Hi chuchienshu,

The error is saying that `FlowWarp` is only defined as a GPU operation, not as a CPU operation. It is trying to run on the CPU which is _not supported_.

Best,
Sam
