### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by chuchienshu** [sampepose/flownet2-tf#8]
```
python3 -m src.flownet2.test --input_a data/samples/0img0.ppm --input_b data/samples/0img1.ppm --out ./
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet2/test.py", line 4, in <module>
    from .flownet2 import FlowNet2
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet2/flownet2.py", line 2, in <module>
    from ..flownet_css.flownet_css import FlowNetCSS
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet_css/flownet_css.py", line 2, in <module>
    from ..flownet_cs.flownet_cs import FlowNetCS
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet_cs/flownet_cs.py", line 2, in <module>
    from ..flownet_c.flownet_c import FlowNetC
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/flownet_c/flownet_c.py", line 3, in <module>
    from ..correlation import correlation
  File "/home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/correlation.py", line 4, in <module>
    tf.resource_loader.get_path_to_datafile("./ops/build/correlation.so"))
  File "/home/chuchienshu/.local/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/chuchienshu/tensorflowcode/newflownet/flownet2-tf/src/./ops/build/correlation.so: undefined symbol: _ZN10tensorflow15shape_inference16InferenceContext8WithRankENS0_11ShapeHandleExPS2_

```

**Comment by jakeoung** [comment]
Same problem.

**Comment by sampepose** [comment]
What OS, gcc version, nvcc version? Did the make process have any warnings or errors? What GPU do you have? Also, I’ve never tried with Python 3, try using Python 2.

I’ll try to repro on Monday once I get that info.

**Comment by jakeoung** [comment]
It seems that tensorflow-gpu 1.3.0 version doesn't work to me. I managed to run the code. For your information, my platform that can run is the following:

tensorflow-gpu (1.0.1)
CUDA 8.0
Ubuntu 14.04

**Comment by HuachunWang** [comment]
You can try it under configurations: gcc4.9, python2.7, Tensorflow1.2.0, cuda8.0, cudnn5.1, GTX TitanX. I have tried Tensorflow1.1.0 and Tensorlfow1.0.1, both did't work. Only Tensorflow1.2.0 did work!

**Comment by alasin** [comment]
Same issue.

**Comment by msokoloff1** [comment]
Is there any update here? Can we get support for tensorflow >= 1.3?

**Comment by msokoloff1** [comment]
Comment out this part of line 56 in the makefile : "-D_GLIBCXX_USE_CXX11_ABI=0". That works for Tensorflow 1.3, cuda 9, titan v

**Comment by xinyangrobotic** [comment]
the same questions with you

**Comment by chenguanqi** [comment]
You can enter "make" command in the terminal under the path of Makefile. Then it will generate the files in need. 
~/flownet2-tf$ make

**Comment by yinjunbo** [comment]
@zxy-HIT @ChenGQ26  
Hi！Could you please tell me have you succeed in training?

**Comment by chenguanqi** [comment]
@yinjunbo 
Hi! I didn‘t try it in training.

**Comment by liruiw** [comment]
Hi! I have the same issue and didn't get resolved by commenting out that line. I'm using tf1.7, cuda9.0 python2.7, gcc5.4 and TitanX as GPU. Thanks!

**Comment by ceciliavision** [comment]
Make sure you used the same python version to compile (specified in Makefile) and run.

**Comment by clausmichele** [comment]
same problem with Python 2.7, Tensorflow 1.4, Cuda 8.0, Ubuntu 16.04. Tried to comment that line before building but nothing changed.

**Comment by mithun2595** [comment]
I faced the same issue with python3, tf 1.5. Fixed it by following this issue https://github.com/tensorflow/tensorflow/issues/13607

**Comment by gongbudaizhe** [comment]
TensorFlow 1.2.1 also works, but not > 1.2.1

**Comment by aa-samad** [comment]
facing the same issues, finally got results #28
